### ISSUE TITLE
Create release and develop branches

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#11]
Create release and develop branches and set up GitFlow

**Comment by Alex180504** [comment]
**User Story:**
As a developement team member,
I want to be able to work on new features in a separate branch,
So that my commits can be tested before put into the main branch.
**Acceptance criteria:**
Given IDE window open
When presss push and select develop branch
Then commits are pushed to the develop branch

**Comment by Alex180504** [comment]
**User Story:**
As a developement team member,
I want to be able publish stable release code in a separate branch,
So that it can be accesed when needed.
**Acceptance criteria:**
Given Github window opena nd new release created
When create pull request and merge
Then release branch is up to date
