### ISSUE TITLE
City Report for region

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#24]
Write an SQL query and Java function to return such information:
"All the cities in a region organised by largest population to smallest"
The function should accept such arguments:
**Region**
The query should return such information:
**Name**
**Country**
**District**
**Population**

**Comment by dsk1ra** [comment]
As a application user,

I want to be able to retrieve a list of all cities in a given region, sorted by population from largest to smallest,

So that I can easily view the most populous cities in a particular region.

Acceptance Criteria:

The system should provide a Java function that accepts a single argument representing the region.
The Java function should execute an SQL query to retrieve the desired information from the database.
The SQL query should return the name, country, district, and population of each city in the specified region, sorted by population in descending order.
The Java function should return the query results as a list of objects, where each object represents a city and contains the name, country, district, and population as properties.
The system should handle any errors or exceptions that may occur during the execution of the function, and return an appropriate error message to the user.
