### ISSUE TITLE
City Report for region(limit N)

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#29]
Write an SQL query and Java function to return such information:
"The top N populated cities in a region where N is provided by the user"
The function should accept such arguments:
**N**
**Region**
The query should return such information:
**Name**
**Country**
**District**
**Population**

**Comment by dsk1ra** [comment]
As a user,

I want to be able to retrieve the top N populated cities in a given region, where N is provided by me,

So that I can easily view the most populous cities in a particular region, up to a specified number.

Acceptance Criteria:

The system should provide a Java function that accepts two arguments: an integer N representing the number of cities to return, and a string Region representing the region to query.
The Java function should execute an SQL query to retrieve the desired information from the database.
The SQL query should return the name, country, district, and population of each city in the specified region, sorted by population in descending order, and limited to the top N results.
The Java function should return the query results as a list of objects, where each object represents a city and contains the name, country, district, and population as properties.
The system should handle any errors or exceptions that may occur during the execution of the function, and return an appropriate error message to the user.
