### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#4]
Create README.md and fill some basic info

**Comment by dsk1ra** [comment]
**User Story:**
As a Scrum Master, I want to create a default project with a README.md file so that team members have a standardized starting point for new projects.

**Acceptance criteria:**
Given a new project setup screen, when I select "Create Default Project" option, then a new project is created with default settings and a README.md file included.

**Comment by dsk1ra** [comment]
**User story 1:**
As a Scrum Master,
I want to automatically create a README.md file with installation instructions when initiating a new project
So that team members have clear guidance on how to set up the project environment.

**Acceptance criteria:**
Given a new project setup screen,
When I select "Create Project",
Then a README.md file is automatically generated within the project directory with basic project information, including clear installation instructions for setting up the project environment.
