### ISSUE TITLE
App Unit Tests

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#44]
Create Unit tests for app service using jupiter and surefire framework

**Comment by dsk1ra** [comment]
As a developer,

I want to create unit tests for the git workflow using Jupiter,

So that I can ensure that the git workflow is functioning correctly and avoid introducing any regressions.

Acceptance Criteria:

The system should provide a set of unit tests that cover the various aspects of the git workflow.
The unit tests should be written using the Jupiter testing framework.
The unit tests should cover scenarios such as:
Initializing a new git repository
Committing changes to the repository
Creating and merging branches
Handling merge conflicts
Tagging releases
Pushing changes to remote repositories
The unit tests should be automated and run as part of the continuous integration pipeline.
The unit tests should provide clear and informative error messages in the event of a failure.
The unit tests should be maintained and updated as the git workflow evolves.
