### ISSUE TITLE
Create Default project

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#6]
Create Default project and push to github

**Comment by dsk1ra** [comment]
**User story:**
As a scrum master,
I want to create a default project,
So that the team can efficiently start working on the Population Management App.

Acceptance criteria:
Given the need to initialize the project,
When I initiate the creation of a default project,
Then the project repository should be cloned from GitHub,
And the Docker image should be built successfully,
And the Docker container should run without errors.

**Comment by Drakon4ik-Coder** [comment]
**User story:**
As a project owner,
I want to create a default project
So that the team can start building other features on top of it
**Acceptance criteria:**
Given the project is pulled from repository
When the project compiles
Then the Docker image is built and  container should run and output numbers from 1 to 5
