### ISSUE TITLE
Query unit tests

### ISSUE THREAD

**Issue by Drakon4ik-Coder** [Drakon4ik-Coder/SET08103_GP#66]
Create Unit tests for query service using jupiter and surefire framework

**Comment by dsk1ra** [comment]
As a developer,

I want to create unit tests for the query workflow using Jupiter,

So that I can ensure that the query workflow is functioning correctly and avoid introducing any regressions.

Acceptance Criteria:

The system should provide a set of unit tests that cover the various aspects of the query workflow.
The unit tests should be written using the Jupiter testing framework.
The unit tests should cover scenarios such as:
Querying for all cities in a region, sorted by population from largest to smallest.
Querying for the top N populated cities in a region, where N is provided by the user.
The unit tests should use a test database with pre-populated data to ensure that the queries are working correctly.
The unit tests should use Mockito to mock any dependencies, such as the database connection.
The unit tests should provide clear and informative error messages in the event of a failure.
The unit tests should be maintained and updated as the query workflow evolves.
